### PR TITLE
Partner logos size

### PR DESCRIPTION
**Pull request by dnsos**
- reduces size of partner logos on smaller screens: `transform: scale(0.5)`
- creates some vertical whitespace between logos on smaller screens -> problematic?

### CODE REVIEW

**Comment by fabianmoronzirfas** [comment]
Hm. Looks wired on Kindle Fire. Screensize 800*1280

Screenshot 2020-03-23 at 12 41 05

**Comment by fabianmoronzirfas** [comment]
iPad 7

Screenshot 2020-03-23 at 12 41 05

**Comment by dnsos** [comment]
Downscaling only applies to screen sizes smaller than tablet now.

**Comment by fabianmoronzirfas** [comment]
@dnsos Is this PR still a thing?

**Comment by dnsos** [comment]
@fabianmoronzirfas yes, I'm taking a look at it today

**Comment by dnsos** [comment]
The scaling solution is reverted.

Taking a look at the Bulma documentation, I don't see how we can use their classes to solve our issue.

**Goal:**
We want the logos to not fill the whole width on mobile, as some get blurry and it all seems out of proportion. In addition, it would make sense to have two logos in a row for mobile, since this makes appropriate use of whitespace.

**Proposal:**
For mobile sizes (and only in the partner logos container), we set `display: inline-block` and `width: 50%`. Styles for tablet and larger screens remain unchanged.

@fabianmoronzirfas can you please review this?

**Comment by fabianmoronzirfas** [comment]
@dnsos Looks good to me. Tested it only in the mobile/responsive viewer of firefox. 

Can you give it a spin in browserstack as well.

About bulma. There are some extra classes for changing display size on mobile. You can find it in the docs of the [columns](https://bulma.io/documentation/columns/responsiveness/). I'm fine with both ways.

**Comment by fabianmoronzirfas** [comment]
Looks fine on diffenrent devices in browserstack. @fdnklg If you don't have anything to say @dnsos can merge this

**Pull request merged**
